name: attendance
description: Anagkazo SMS attendance app

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  google_fonts: ^4.0.3
  parse_server_sdk_flutter: ^3.1.3
  get_it: ^7.2.0
  injectable: ^2.1.0
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  auto_route: ^5.0.4
  line_awesome_flutter: ^2.0.0
  moment_dart: ^0.17.0
  json_annotation: ^4.8.0
  responsive_framework: ^0.2.0
  flex_color_scheme: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.4
  build_runner: ^2.3.3
  freezed: ^2.3.2
  auto_route_generator: ^5.0.3
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
