name: attendance
description: Anagkazo SMS attendance app

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  google_fonts: ^4.0.3
  parse_server_sdk_flutter: ^3.1.3
  get_it: ^7.2.0
  injectable: ^2.1.0
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  auto_route: ^5.0.4
  line_awesome_flutter: ^2.0.0
  moment_dart: ^0.17.0
  json_annotation: ^4.8.0
  responsive_framework: ^0.2.0
  flex_color_scheme: ^6.1.2
  custom_qr_generator: ^0.1.2
  flutter_native_splash: ^2.2.17
  flutter_spinkit: ^5.1.0
  to_csv: ^1.1.1
  google_nav_bar: ^5.0.6
  skeletons: ^0.0.3
  share_plus: ^6.3.1
  # connectivity_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.4
  build_runner: ^2.3.3
  freezed: ^2.3.2
  auto_route_generator: ^5.0.3
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon_bg.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/android12_icon.png"

flutter_native_splash:
  color: "#F0E9EA"
  color_dark: "#141313"
  image: "assets/icon/attendance_splash.png"
  image_dark: "assets/icon/attendance_splash_dark.png"
  android: true
  ios: true
  android_12:
    color: "#F0E9EA"
    color_dark: "#141313"
    image: "assets/icon/attendance_splash.png"
    image_dark: "assets/icon/attendance_splash_dark.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
    - assets/scan/
    - assets/illustrations/
  


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
